### ISSUE TITLE
スポンサーは募集しますか？

### ISSUE THREAD

**Issue by Nkzn** [DroidKaigi/QA#2]
今回、または今後、運営資金の確保のためにスポンサー制度を設ける可能性はありますか？

**Comment by mhidaka** [comment]
ぶっちゃけ、お金はあったほうがいいので、とても正しい疑問だと思います。

今回のDroidKaigiは、会場提供のサイバーエージェントさん以外にスポンサーさんはいらっしゃいません。
運営資金については実行委員会で持ち出しの状況ですが、現時点では、スポンサー制度等は未整備です。
今回は、そのあたりを気にするより費用をなるべくかけず、飲み込める範囲で（なるべくお金かけないように）実施して、コミュニケーション、技術共有の場を作ろう、という部分を優先しています。

もしスポンサー制度を用意する場合、リワードの設定やお金の取り扱いなどの仕組みが必要ですので更なる議論が必要と認識してます。つまるところ、今後は未定です。

**Comment by Nkzn** [comment]
回答ありがとうございます。お金をかければ良いイベントになるわけでもありませんので、よい方針だと思いました。
実行委員会の皆さんのご負担ばかりが大きくならないよう、参加者全体で面白いイベントになるように盛り上げていけたらよいですね。
